In [1]:
import xarray as xr
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import glob

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
%pprint

Pretty printing has been turned OFF

In [4]:
## use regridded cmip data as check
cmip_dir = "/davenport-scratch/fvdav22/projects/extreme-precip-trends/processed_data/CMIP6/"

In [5]:
def check_simulations(freq, var): 
    dat = []
    files = glob.glob(cmip_dir+var+"_"+freq+"*5x5.nc")
    for f in files: 
        ds = xr.open_dataset(f)
        m = f.split("/")[-1].split("_")[2]
        v = f.split("/")[-1].split("_")[5]
        d = pd.DataFrame({'freq': [freq], 'var': [var], 'model': [m], 'variant': [v], 'length': [len(ds.time)], 
                          'start_date': [ds.time[0].values], 'end_date': [ds.time[-1].values]})
        dat.append(d)

    dat = pd.concat(dat)
    dat.to_csv("../processed_data/simulation_table_"+freq+"_"+var+".csv", index = False)

    return(dat)

In [6]:
check_simulations("mon", "pr")

,freq,var,model,variant,length,start_date,end_date
0,mon,pr,CanESM5,r8i1p1f1,3012,1850-01-16 12:00:00,2100-12-16 12:00:00
0,mon,pr,ACCESS-CM2,r1i1p1f1,3012,1850-01-16 12:00:00,2100-12-16 12:00:00
0,mon,pr,ACCESS-ESM1-5,r29i1p1f1,3012,1850-01-16 12:00:00,2100-12-16 12:00:00
0,mon,pr,CanESM5,r19i1p1f1,3012,1850-01-16 12:00:00,2100-12-16 12:00:00
0,mon,pr,FGOALS-g3,r1i1p1f1,3012,1850-01-16 12:00:00,2100-12-16 12:00:00
...,...,...,...,...,...,...,...
0,mon,pr,ACCESS-ESM1-5,r38i1p1f1,3012,1850-01-16 12:00:00,2100-12-16 12:00:00
0,mon,pr,CanESM5-1,r2i1p1f1,3012,1850-01-16 12:00:00,2100-12-16 12:00:00
0,mon,pr,EC-Earth3,r136i1p1f1,1572,1970-01-16 12:00:00,2100-12-16 12:00:00
0,mon,pr,EC-Earth3-Veg-LR,r1i1p1f1,3012,1850-01-16 12:00:00,2100-12-16 12:00:00
0,mon,pr,CNRM-CM6-1,r5i1p1f2,3012,1850-01-16 12:00:00,2100-12-16 12:00:00

In [7]:
check_simulations("day", "pr")

,freq,var,model,variant,length,start_date,end_date
0,day,pr,EC-Earth3,r136i1p1f1,47847,1970-01-01 12:00:00,2100-12-31 12:00:00
0,day,pr,MRI-ESM2-0,r1i1p1f1,91676,1850-01-01 12:00:00,2100-12-31 12:00:00
0,day,pr,MIROC6,r31i1p1f1,91676,1850-01-01 12:00:00,2100-12-31 12:00:00
0,day,pr,EC-Earth3-Veg,r2i1p1f1,91676,1850-01-01 12:00:00,2100-12-31 12:00:00
0,day,pr,MPI-ESM1-2-LR,r7i1p1f1,91676,1850-01-01 12:00:00,2100-12-31 12:00:00
...,...,...,...,...,...,...,...
0,day,pr,MIROC6,r3i1p1f1,91676,1850-01-01 12:00:00,2100-12-31 12:00:00
0,day,pr,CanESM5,r24i1p1f1,91615,1850-01-01 12:00:00,2100-12-31 12:00:00
0,day,pr,EC-Earth3,r127i1p1f1,47847,1970-01-01 12:00:00,2100-12-31 12:00:00
0,day,pr,CESM2,r4i1p1f1,91615,1850-01-01 00:00:00,2100-12-31 00:00:00
0,day,pr,MIROC6,r20i1p1f1,91676,1850-01-01 12:00:00,2100-12-31 12:00:00